# Generated by Django 5.1.3 on 2024-12-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='Full_name',
        ),
        migrations.AlterField(
            model_name='contract',
            name='signature1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signature2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
