# Generated by Django 5.1.3 on 2024-12-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_creator_contract_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signature1',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signature2',
        ),
        migrations.AddField(
            model_name='contract',
            name='envelope_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
