# Generated by Django 5.1.3 on 2024-12-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_contract_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_signed_by_creator',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_signed_by_recipient',
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
